-- Database Schema for Admission Inquiry Form Data
-- Table: admission_inquiries

CREATE TABLE IF NOT EXISTS public.admission_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  student_name TEXT NOT NULL,
  grade TEXT NOT NULL,
  parent_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  message TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.admission_inquiries ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous form submissions
CREATE POLICY "Allow public form submissions"
ON public.admission_inquiries
FOR INSERT
WITH CHECK (true);

-- Allow authenticated/service users to view submissions
CREATE POLICY "Allow authenticated read"
ON public.admission_inquiries
FOR SELECT
USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
